version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - ./sql_volume_2:/var/lib/mysql
  mongo:
    image: mongo
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./mongo_volumes:/data/db